functionsDir: ./spectral-functions
functions:
  - arcsecBoundary

rules:
  info-contact:
    description: Arcsec contained boundary canary v2
    message: "{{error}}"
    severity: error
    given: $
    then:
      function: arcsecBoundary
